# This is a configuration file for the bacon tool
# More info at https://github.com/Canop/bacon
#
# Ideas "borrowed" from egui

default_job = "check"

[jobs.check]
command = ["cargo", "check", "--color", "always"]
need_stdout = false

[jobs.check-all]
command = ["cargo", "check", "--all-targets", "--color", "always"]
need_stdout = false

[jobs.clippy]
command = [
    "cargo", "clippy",
    "--all-targets",
    "--color", "always",
    "--", "-D", "warnings",
]
need_stdout = false

[jobs.test]
command = ["cargo", "test", "--color=always"]
need_stdout = true
watch = ["tests"]


[jobs.fmt]
command = ["cargo", "fmt", "--all", "--", "--check"]

[jobs.doc]
command = ["cargo", "doc", "--color=always", "--all-features", "--no-deps"]
need_stdout = false

# if the doc compiles, then it opens in your browser and bacon switches
# to the previous job
[jobs.doc-open]
command = [
    "cargo",
    "doc",
    "--color=always",
    "--all-features",
    "--no-deps",
    "--open",
]
need_stdout = false
on_success = "back" # so that we don't open the browser at each change

# You can run your application and have the result displayed in bacon,
# *if* it makes sense for this crate. You can run an example the same
# way. Don't forget the `--color always` part or the errors won't be
# properly parsed.
[jobs.run]
command = ["cargo", "run", "--color=always"]
need_stdout = true


# You may define here keybindings that would be specific to
# a project, for example a shortcut to launch a specific job.
# Shortcuts to internal functions (scrolling, toggling, etc.)
# should go in your personal prefs.toml file instead.
[keybindings]
i = "job:initial"
d = "job:doc-open"
t = "job:test"
r = "job:run"
c = "job:clippy"
k = "job:check"
f = "job:fmt"