[package]
name = "mars_raw_utils"
version = "0.1.4"
authors = ["Kevin M. Gill <apoapsys@gmail.com>"]
edition = "2018"
description = "Utilities for working with publicly available raw MSL, Mars2020, and InSight images"
repository = "https://github.com/kmgill/mars-raw-utils"
readme = "README.md"
keywords = ["mars", "msl", "mars2020", "insight"]
license = "MIT" 
exclude = ["mars-raw-utils-data"]

[package.metadata.deb]
maintainer = "Kevin M. Gill <apoapsys@gmail.com>"
copyright = "2021, Kevin M. Gill <apoapsys@gmail.com>"
license-file = ["LICENSE", "2"]
extended-description = "Utilities for working with publicly available raw MSL, Mars2020, and InSight images" 
depends = "$auto"
section = "science"
priority = "optional"
assets = [
    ["target/release/msl_fetch_raw", "usr/bin/", "755"],
    ["target/release/msl_mahli_calibrate", "usr/bin/", "755"],
    ["target/release/msl_mcam_calibrate", "usr/bin/", "755"],
    ["target/release/msl_ecam_calibrate", "usr/bin/", "755"],
    ["target/release/msl_ccam_calibrate", "usr/bin/", "755"],
    ["target/release/msl_mardi_calibrate", "usr/bin/", "755"],
    ["target/release/m20_ecam_calibrate", "usr/bin/", "755"],
    ["target/release/m20_fetch_raw", "usr/bin/", "755"],
    ["target/release/m20_watson_calibrate", "usr/bin/", "755"],
    ["target/release/m20_zcam_calibrate", "usr/bin/", "755"],
    ["target/release/m20_scam_calibrate", "usr/bin/", "755"],
    ["target/release/hpc_filter", "usr/bin/", "755"],
    ["target/release/nsyt_icc_calibrate", "usr/bin/", "755"],
    ["target/release/nsyt_idc_calibrate", "usr/bin/", "755"],
    ["target/release/nsyt_fetch_raw", "usr/bin/", "755"],
    ["target/release/inpaint_filter", "usr/bin/", "755"],
    ["target/release/upscale", "usr/bin/", "755"],
    ["target/release/msl_date", "usr/bin/", "755"],
    ["target/release/m20_date", "usr/bin/", "755"],
    ["target/release/nsyt_date", "usr/bin/", "755"],
    ["target/release/crop", "usr/bin/", "755"],
    ["target/release/debayer", "usr/bin/", "755"],
    ["README.md", "usr/share/doc/mars_raw_utils/README", "644"],
    ["mars-raw-utils-data/caldata/*png", "usr/share/mars_raw_utils/data/", "644"],
    ["mars-raw-utils-data/caldata/*jpg", "usr/share/mars_raw_utils/data/", "644"],
    ["mars-raw-utils-data/caldata/caldata.toml", "usr/share/mars_raw_utils/data/", "644"],
]

[lib]
name = "mars_raw_utils"

[[bin]]
name = "msl_mahli_calibrate"
path = "bin/msl_mahli_calibrate.rs"

[[bin]]
name = "msl_mcam_calibrate"
path = "bin/msl_mcam_calibrate.rs"

[[bin]]
name = "msl_ccam_calibrate"
path = "bin/msl_ccam_calibrate.rs"

[[bin]]
name = "msl_mardi_calibrate"
path = "bin/msl_mardi_calibrate.rs"

[[bin]]
name = "m20_zcam_calibrate"
path = "bin/m20_zcam_calibrate.rs"

[[bin]]
name = "msl_fetch_raw"
path = "bin/msl_fetch_raw.rs"

[[bin]]
name = "m20_fetch_raw"
path = "bin/m20_fetch_raw.rs"

[[bin]]
name = "nsyt_fetch_raw"
path = "bin/nsyt_fetch_raw.rs"

[[bin]]
name = "nsyt_icc_calibrate"
path = "bin/nsyt_icc_calibrate.rs"

[[bin]]
name = "nsyt_idc_calibrate"
path = "bin/nsyt_idc_calibrate.rs"

[[bin]]
name = "msl_ecam_calibrate"
path = "bin/msl_ecam_calibrate.rs"

[[bin]]
name = "hpc_filter"
path = "bin/hpc_filter.rs"

[[bin]]
name = "m20_ecam_calibrate"
path = "bin/m20_ecam_calibrate.rs"

[[bin]]
name = "m20_watson_calibrate"
path = "bin/m20_watson_calibrate.rs"

[[bin]]
name = "m20_scam_calibrate"
path = "bin/m20_scam_calibrate.rs"

[[bin]]
name = "inpaint_filter"
path = "bin/inpaint_filter.rs"

[[bin]]
name = "upscale"
path = "bin/upscale.rs"

[[bin]]
name = "msl_date"
path = "bin/msl_date.rs"

[[bin]]
name = "m20_date"
path = "bin/m20_date.rs"

[[bin]]
name = "nsyt_date"
path = "bin/nsyt_date.rs"

[[bin]]
name = "crop"
path = "bin/crop.rs"

[[bin]]
name = "debayer"
path = "bin/debayer.rs"

[features]

[dependencies]
image = "0.23.14"
clap = "2.33.3"
serde_json = "1.0.64"
const_format = "0.2.14"
reqwest = { version = "0.11.2", features = ["blocking"] }
platforms = "1.1.0"
fastblur = "0.1.1"
lab = "0.10.0"
toml = "0.5.8"
serde = { version = "1.0.125", features = ["derive"] }
sscanf = "0.1.1"
string-builder = "0.2.0"

[package.metadata.rpm]
package = "mars_raw_utils"

[package.metadata.rpm.cargo]
buildflags = ["--release"]

[package.metadata.rpm.targets]
hpc_filter = { path = "/usr/bin/hpc_filter" }
inpaint_filter = { path = "/usr/bin/inpaint_filter" }
m20_ecam_calibrate = { path = "/usr/bin/m20_ecam_calibrate" }
m20_fetch_raw = { path = "/usr/bin/m20_fetch_raw" }
m20_scam_calibrate = { path = "/usr/bin/m20_scam_calibrate" }
m20_watson_calibrate = { path = "/usr/bin/m20_watson_calibrate" }
m20_zcam_calibrate = { path = "/usr/bin/m20_zcam_calibrate" }
msl_ecam_calibrate = { path = "/usr/bin/msl_ecam_calibrate" }
msl_fetch_raw = { path = "/usr/bin/msl_fetch_raw" }
msl_mahli_calibrate = { path = "/usr/bin/msl_mahli_calibrate" }
msl_mcam_calibrate = { path = "/usr/bin/msl_mcam_calibrate" }
msl_ccam_calibrate = { path = "/usr/bin/msl_ccam_calibrate" }
msl_mardi_calibrate = { path = "/usr/bin/msl_mardi_calibrate" }
nsyt_icc_calibrate = { path = "/usr/bin/nsyt_icc_calibrate" }
nsyt_idc_calibrate = { path = "/usr/bin/nsyt_idc_calibrate" }
nsyt_fetch_raw = { path = "/usr/bin/nsyt_fetch_raw" }
upscale = { path = "/usr/bin/upscale" }
msl_date = { path = "/usr/bin/msl_date" }
m20_date = { path = "/usr/bin/m20_date" }
nsyt_date = { path = "/usr/bin/nsyt_date" }
debayer = { path = "/usr/bin/debayer" }
crop = { path = "/usr/bin/crop" }

[package.metadata.rpm.files]
"M20_MCZ_LEFT_INPAINT_MASK_V1.png" = { path =  "/usr/share/mars_raw_utils/data/M20_MCZ_LEFT_INPAINT_MASK_V1.png", mode = "644"}
"M20_MCZ_RIGHT_INPAINT_MASK_V1.png" = { path =  "/usr/share/mars_raw_utils/data/M20_MCZ_RIGHT_INPAINT_MASK_V1.png", mode = "644"}
"M20_SCAM_FLAT_RGB_Sol77_V2.png" = { path =  "/usr/share/mars_raw_utils/data/M20_SCAM_FLAT_RGB_Sol77_V2.png", mode = "644"}
"M20_SCAM_MASK_Sol1_V1.png" = { path =  "/usr/share/mars_raw_utils/data/M20_SCAM_MASK_Sol1_V1.png", mode = "644"}
"M20_WATSON_FLAT_V0.png" = { path =  "/usr/share/mars_raw_utils/data/M20_WATSON_FLAT_V0.png", mode = "644"}
"M20_WATSON_INPAINT_MASK_V1.png" = { path =  "/usr/share/mars_raw_utils/data/M20_WATSON_INPAINT_MASK_V1.png", mode = "644"}
"MSL_FLB_FLAT_V1.png" = { path =  "/usr/share/mars_raw_utils/data/MSL_FLB_FLAT_V1.png", mode = "644"}
"MSL_FRB_FLAT_V1.png" = { path =  "/usr/share/mars_raw_utils/data/MSL_FRB_FLAT_V1.png", mode = "644"}
"MSL_MAHLI_FLAT_Sol2904_V1.png" = { path =  "/usr/share/mars_raw_utils/data/MSL_MAHLI_FLAT_Sol2904_V1.png", mode = "644"}
"MSL_MAHLI_INPAINT_Sol2904_V1.png" = { path =  "/usr/share/mars_raw_utils/data/MSL_MAHLI_INPAINT_Sol2904_V1.png", mode = "644"}
"MSL_MCAM_LEFT_INPAINT_Sol3082_V1.png" = { path =  "/usr/share/mars_raw_utils/data/MSL_MCAM_LEFT_INPAINT_Sol3082_V1.png", mode = "644"}
"MSL_NLB_FLAT_V1.png" = { path =  "/usr/share/mars_raw_utils/data/MSL_NLB_FLAT_V1.png", mode = "644"}
"MSL_NRB_FLAT_V1.png" = { path =  "/usr/share/mars_raw_utils/data/MSL_NRB_FLAT_V1.png", mode = "644"}
"MSL_NRB_INPAINT_Sol3052_V1.png" = { path =  "/usr/share/mars_raw_utils/data/MSL_NRB_INPAINT_Sol3052_V1.png", mode = "644"}
"MSL_RLB_FLAT_V1.png" = { path =  "/usr/share/mars_raw_utils/data/MSL_RLB_FLAT_V1.png", mode = "644"}
"MSL_RRB_FLAT_V1.png" = { path =  "/usr/share/mars_raw_utils/data/MSL_RRB_FLAT_V1.png", mode = "644"}
"MSL_CCAM_MASK_Sol3122_V2.png" = { path =  "/usr/share/mars_raw_utils/data/MSL_CCAM_MASK_Sol3122_V2.png", mode = "644"}
"MSL_CCAM_FLAT_Sol32_V1.png" = { path =  "/usr/share/mars_raw_utils/data/MSL_CCAM_FLAT_Sol32_V1.png", mode = "644"}
"FLAT_MD_0_RGB_V1.jpg" = { path =  "/usr/share/mars_raw_utils/data/FLAT_MD_0_RGB_V1.jpg", mode = "644"}
"NSYT_FLAT_SN_0203.jpg" = { path =  "/usr/share/mars_raw_utils/data/NSYT_FLAT_SN_0203.jpg", mode = "644"}
"NSYT_FLAT_SN_0210.jpg" = { path =  "/usr/share/mars_raw_utils/data/NSYT_FLAT_SN_0210.jpg", mode = "644"}
"caldata.toml" = { path =  "/usr/share/mars_raw_utils/data/caldata.toml", mode = "644"}


