[package]
name = "mars_raw_utils"
version = "0.3.1"
authors = ["Kevin M. Gill <apoapsys@gmail.com>"]
edition = "2018"
description = "Utilities for working with publicly available raw MSL, Mars2020, and InSight images"
repository = "https://github.com/kmgill/mars-raw-utils"
readme = "README.md"
keywords = ["mars", "msl", "mars2020", "insight"]
license = "MIT" 
exclude = ["mars-raw-utils-data"]

[package.metadata.deb]
maintainer = "Kevin M. Gill <apoapsys@gmail.com>"
copyright = "2022, Kevin M. Gill <apoapsys@gmail.com>"
license-file = ["LICENSE", "2"]
extended-description = "Utilities for working with publicly available raw MSL, Mars2020, and InSight images" 
depends = "$auto"
section = "science"
priority = "optional"
assets = [
    ["target/release/msl_fetch_raw", "usr/bin/", "755"],
    ["target/release/msl_latest", "usr/bin/", "755"],
    ["target/release/msl_mahli_calibrate", "usr/bin/", "755"],
    ["target/release/msl_mcam_calibrate", "usr/bin/", "755"],
    ["target/release/msl_ecam_calibrate", "usr/bin/", "755"],
    ["target/release/msl_ccam_calibrate", "usr/bin/", "755"],
    ["target/release/msl_mardi_calibrate", "usr/bin/", "755"],
    ["target/release/m20_ecam_assemble", "usr/bin/", "755"],
    ["target/release/m20_ecam_calibrate", "usr/bin/", "755"],
    ["target/release/m20_fetch_raw", "usr/bin/", "755"],
    ["target/release/m20_latest", "usr/bin/", "755"],
    ["target/release/m20_watson_calibrate", "usr/bin/", "755"],
    ["target/release/m20_zcam_calibrate", "usr/bin/", "755"],
    ["target/release/m20_scam_calibrate", "usr/bin/", "755"],
    ["target/release/m20_hnav_calibrate", "usr/bin/", "755"],
    ["target/release/m20_hrte_calibrate", "usr/bin/", "755"],
    ["target/release/hpc_filter", "usr/bin/", "755"],
    ["target/release/nsyt_icc_calibrate", "usr/bin/", "755"],
    ["target/release/nsyt_idc_calibrate", "usr/bin/", "755"],
    ["target/release/nsyt_fetch_raw", "usr/bin/", "755"],
    ["target/release/nsyt_latest", "usr/bin/", "755"],
    ["target/release/inpaint_filter", "usr/bin/", "755"],
    ["target/release/upscale", "usr/bin/", "755"],
    ["target/release/msl_date", "usr/bin/", "755"],
    ["target/release/m20_date", "usr/bin/", "755"],
    ["target/release/nsyt_date", "usr/bin/", "755"],
    ["target/release/crop", "usr/bin/", "755"],
    ["target/release/debayer", "usr/bin/", "755"],
    ["target/release/gen_mean_stack", "usr/bin/", "755"],
    ["target/release/levels", "usr/bin/", "755"],
    ["target/release/diffgif", "usr/bin/", "755"],
    ["target/release/focusmerge", "usr/bin/", "755"],
    ["README.md", "usr/share/doc/mars_raw_utils/README", "644"],
    ["mars-raw-utils-data/caldata/*png", "usr/share/mars_raw_utils/data/", "644"],
    ["mars-raw-utils-data/caldata/*jpg", "usr/share/mars_raw_utils/data/", "644"],
    ["mars-raw-utils-data/caldata/*.toml", "usr/share/mars_raw_utils/data/", "644"],
]

[lib]
name = "mars_raw_utils"

[[bin]]
name = "msl_mahli_calibrate"
path = "bin/msl_mahli_calibrate.rs"

[[bin]]
name = "msl_mcam_calibrate"
path = "bin/msl_mcam_calibrate.rs"

[[bin]]
name = "msl_ccam_calibrate"
path = "bin/msl_ccam_calibrate.rs"

[[bin]]
name = "msl_mardi_calibrate"
path = "bin/msl_mardi_calibrate.rs"

[[bin]]
name = "m20_zcam_calibrate"
path = "bin/m20_zcam_calibrate.rs"

[[bin]]
name = "m20_hnav_calibrate"
path = "bin/m20_hnav_calibrate.rs"

[[bin]]
name = "m20_hrte_calibrate"
path = "bin/m20_hrte_calibrate.rs"

[[bin]]
name = "msl_fetch_raw"
path = "bin/msl_fetch_raw.rs"

[[bin]]
name = "msl_latest"
path = "bin/msl_latest.rs"

[[bin]]
name = "m20_fetch_raw"
path = "bin/m20_fetch_raw.rs"

[[bin]]
name = "m20_latest"
path = "bin/m20_latest.rs"

[[bin]]
name = "nsyt_fetch_raw"
path = "bin/nsyt_fetch_raw.rs"

[[bin]]
name = "nsyt_latest"
path = "bin/nsyt_latest.rs"

[[bin]]
name = "nsyt_icc_calibrate"
path = "bin/nsyt_icc_calibrate.rs"

[[bin]]
name = "nsyt_idc_calibrate"
path = "bin/nsyt_idc_calibrate.rs"

[[bin]]
name = "msl_ecam_calibrate"
path = "bin/msl_ecam_calibrate.rs"

[[bin]]
name = "hpc_filter"
path = "bin/hpc_filter.rs"

[[bin]]
name = "m20_ecam_assemble"
path = "bin/m20_ecam_assemble.rs"

[[bin]]
name = "m20_ecam_calibrate"
path = "bin/m20_ecam_calibrate.rs"

[[bin]]
name = "m20_watson_calibrate"
path = "bin/m20_watson_calibrate.rs"

[[bin]]
name = "m20_scam_calibrate"
path = "bin/m20_scam_calibrate.rs"

[[bin]]
name = "inpaint_filter"
path = "bin/inpaint_filter.rs"

[[bin]]
name = "upscale"
path = "bin/upscale.rs"

[[bin]]
name = "msl_date"
path = "bin/msl_date.rs"

[[bin]]
name = "m20_date"
path = "bin/m20_date.rs"

[[bin]]
name = "nsyt_date"
path = "bin/nsyt_date.rs"

[[bin]]
name = "crop"
path = "bin/crop.rs"

[[bin]]
name = "debayer"
path = "bin/debayer.rs"

[[bin]]
name = "gen_mean_stack"
path = "bin/gen_mean_stack.rs"

[[bin]]
name = "levels"
path = "bin/levels.rs"

[[bin]]
name = "diffgif"
path = "bin/diffgif.rs"

[[bin]]
name = "focusmerge"
path = "bin/focusmerge.rs"

[features]

[dependencies]
image = "0.23.14"
clap = "2.33.3"
serde_json = "1.0.64"
const_format = "0.2.14"
reqwest = { version = "0.11.2", features = ["blocking"] }
platforms = "2.0.0"
lab = "0.11.0"
toml = "0.5.8"
serde = { version = "1.0.125", features = ["derive"] }
string-builder = "0.2.0"
sciimg = "0.2.4"
#sciimg = { path = "../sciimg" }
weezl = "0.1.5"
gif = "0.11.3"
rayon = "1.5.1"
chrono = "0.4.19"
dirs = "4.0.0"

[package.metadata.rpm]
package = "mars_raw_utils"

[package.metadata.rpm.cargo]
buildflags = ["--release"]

[package.metadata.rpm.targets]
hpc_filter = { path = "/usr/bin/hpc_filter" }
inpaint_filter = { path = "/usr/bin/inpaint_filter" }
m20_ecam_calibrate = { path = "/usr/bin/m20_ecam_calibrate" }
m20_fetch_raw = { path = "/usr/bin/m20_fetch_raw" }
m20_latest = { path = "/usr/bin/m20_latest" }
m20_scam_calibrate = { path = "/usr/bin/m20_scam_calibrate" }
m20_watson_calibrate = { path = "/usr/bin/m20_watson_calibrate" }
m20_zcam_calibrate = { path = "/usr/bin/m20_zcam_calibrate" }
m20_hnav_calibrate = { path = "/usr/bin/m20_hnav_calibrate" }
m20_hrte_calibrate = { path = "/usr/bin/m20_hrte_calibrate" }
m20_ecam_assemble = { path = "/usr/bin/m20_ecam_assemble" }
msl_ecam_calibrate = { path = "/usr/bin/msl_ecam_calibrate" }
msl_fetch_raw = { path = "/usr/bin/msl_fetch_raw" }
msl_latest = { path = "/usr/bin/msl_latest" }
msl_mahli_calibrate = { path = "/usr/bin/msl_mahli_calibrate" }
msl_mcam_calibrate = { path = "/usr/bin/msl_mcam_calibrate" }
msl_ccam_calibrate = { path = "/usr/bin/msl_ccam_calibrate" }
msl_mardi_calibrate = { path = "/usr/bin/msl_mardi_calibrate" }
nsyt_icc_calibrate = { path = "/usr/bin/nsyt_icc_calibrate" }
nsyt_idc_calibrate = { path = "/usr/bin/nsyt_idc_calibrate" }
nsyt_fetch_raw = { path = "/usr/bin/nsyt_fetch_raw" }
nsyt_latest = { path = "/usr/bin/nsyt_latest" }
upscale = { path = "/usr/bin/upscale" }
msl_date = { path = "/usr/bin/msl_date" }
m20_date = { path = "/usr/bin/m20_date" }
nsyt_date = { path = "/usr/bin/nsyt_date" }
debayer = { path = "/usr/bin/debayer" }
crop = { path = "/usr/bin/crop" }
gen_mean_stack = { path = "/usr/bin/gen_mean_stack" }
diffgif = { path = "/usr/bin/diffgif" }
levels = { path = "/usr/bin/levels" }
focusmerge = { path = "/usr/bin/focusmerge" }

[package.metadata.rpm.files]
"M20_MCZ_LEFT_INPAINT_MASK_V1.png" = { path =  "/usr/share/mars_raw_utils/data/M20_MCZ_LEFT_INPAINT_MASK_V1.png", mode = "644"}
"M20_MCZ_RIGHT_INPAINT_MASK_V1.png" = { path =  "/usr/share/mars_raw_utils/data/M20_MCZ_RIGHT_INPAINT_MASK_V1.png", mode = "644"}
"M20_SCAM_FLAT_RGB_Sol77_V2.png" = { path =  "/usr/share/mars_raw_utils/data/M20_SCAM_FLAT_RGB_Sol77_V2.png", mode = "644"}
"M20_SCAM_MASK_Sol1_V1.png" = { path =  "/usr/share/mars_raw_utils/data/M20_SCAM_MASK_Sol1_V1.png", mode = "644"}
"M20_WATSON_FLAT_V0.png" = { path =  "/usr/share/mars_raw_utils/data/M20_WATSON_FLAT_V0.png", mode = "644"}
"M20_WATSON_INPAINT_MASK_V1.png" = { path =  "/usr/share/mars_raw_utils/data/M20_WATSON_INPAINT_MASK_V1.png", mode = "644"}
"M20_HELI_NAV_FLAT_Sol76_V1.jpg" = { path =  "/usr/share/mars_raw_utils/data/M20_HELI_NAV_FLAT_Sol76_V1.jpg", mode = "644"}
"M20_HELI_RTE_FLAT_V3.png" = { path =  "/usr/share/mars_raw_utils/data/M20_HELI_RTE_FLAT_V3.png", mode = "644"}
"MSL_FLB_FLAT_V1.png" = { path =  "/usr/share/mars_raw_utils/data/MSL_FLB_FLAT_V1.png", mode = "644"}
"MSL_FRB_FLAT_V1.png" = { path =  "/usr/share/mars_raw_utils/data/MSL_FRB_FLAT_V1.png", mode = "644"}
"MSL_MAHLI_FLAT_Sol2904_V1.png" = { path =  "/usr/share/mars_raw_utils/data/MSL_MAHLI_FLAT_Sol2904_V1.png", mode = "644"}
"MSL_MAHLI_INPAINT_Sol2904_V1.png" = { path =  "/usr/share/mars_raw_utils/data/MSL_MAHLI_INPAINT_Sol2904_V1.png", mode = "644"}
"MSL_MCAM_LEFT_INPAINT_Sol3082_V1.png" = { path =  "/usr/share/mars_raw_utils/data/MSL_MCAM_LEFT_INPAINT_Sol3082_V1.png", mode = "644"}
"MSL_NLB_FLAT_V1.png" = { path =  "/usr/share/mars_raw_utils/data/MSL_NLB_FLAT_V1.png", mode = "644"}
"MSL_NRB_FLAT_V1.png" = { path =  "/usr/share/mars_raw_utils/data/MSL_NRB_FLAT_V1.png", mode = "644"}
"MSL_NRB_INPAINT_Sol3052_V1.png" = { path =  "/usr/share/mars_raw_utils/data/MSL_NRB_INPAINT_Sol3052_V1.png", mode = "644"}
"MSL_RLB_FLAT_V1.png" = { path =  "/usr/share/mars_raw_utils/data/MSL_RLB_FLAT_V1.png", mode = "644"}
"MSL_RRB_FLAT_V1.png" = { path =  "/usr/share/mars_raw_utils/data/MSL_RRB_FLAT_V1.png", mode = "644"}
"MSL_CCAM_MASK_Sol3122_V2.png" = { path =  "/usr/share/mars_raw_utils/data/MSL_CCAM_MASK_Sol3122_V2.png", mode = "644"}
"MSL_CCAM_FLAT_Sol32_V1.png" = { path =  "/usr/share/mars_raw_utils/data/MSL_CCAM_FLAT_Sol32_V1.png", mode = "644"}
"FLAT_MD_0_RGB_V1.jpg" = { path =  "/usr/share/mars_raw_utils/data/FLAT_MD_0_RGB_V1.jpg", mode = "644"}
"NSYT_FLAT_SN_0203.jpg" = { path =  "/usr/share/mars_raw_utils/data/NSYT_FLAT_SN_0203.jpg", mode = "644"}
"NSYT_FLAT_SN_0210.jpg" = { path =  "/usr/share/mars_raw_utils/data/NSYT_FLAT_SN_0210.jpg", mode = "644"}
"caldata.toml" = { path =  "/usr/share/mars_raw_utils/data/caldata.toml", mode = "644"}
"msl_mcam_bay.toml" = { path =  "/usr/share/mars_raw_utils/data/msl_mcam_bay.toml", mode = "644"}
"msl_mcam_ilt.toml" = { path =  "/usr/share/mars_raw_utils/data/msl_mcam_ilt.toml", mode = "644"}
"msl_mcam_rad.toml" = { path =  "/usr/share/mars_raw_utils/data/msl_mcam_rad.toml", mode = "644"}
"msl_mahli_bay.toml" = { path =  "/usr/share/mars_raw_utils/data/msl_mahli_bay.toml", mode = "644"}
"msl_mahli_ilt.toml" = { path =  "/usr/share/mars_raw_utils/data/msl_mahli_ilt.toml", mode = "644"}
"msl_mahli_rad.toml" = { path =  "/usr/share/mars_raw_utils/data/msl_mahli_rad.toml", mode = "644"}
"msl_mahli_cwb.toml" = { path =  "/usr/share/mars_raw_utils/data/msl_mahli_cwb.toml", mode = "644"}