[package]
name = "mars_raw_utils"
version = "0.1.1"
authors = ["Kevin M. Gill <apoapsys@gmail.com>"]
edition = "2018"
description = "Utilities for working with publicly available raw MSL, Mars2020, and InSight images"
repository = "https://github.com/kmgill/mars-raw-utils"
readme = "README.md"
keywords = ["mars", "msl", "mars2020"]
license = "MIT" 

[package.metadata.deb]
maintainer = "Kevin M. Gill <apoapsys@gmail.com>"
copyright = "2021, Kevin M. Gill <apoapsys@gmail.com>"
license-file = ["LICENSE", "2"]
extended-description = "Utilities for working with publicly available raw MSL, Mars2020, and InSight images" 
depends = "$auto"
section = "science"
priority = "optional"
assets = [
    ["target/release/msl_fetch_raw", "usr/bin/", "755"],
    ["target/release/msl_mahli_calibrate", "usr/bin/", "755"],
    ["target/release/msl_mcam_calibrate", "usr/bin/", "755"],
    ["target/release/msl_ecam_calibrate", "usr/bin/", "755"],
    ["target/release/m20_ecam_calibrate", "usr/bin/", "755"],
    ["target/release/m20_fetch_raw", "usr/bin/", "755"],
    ["target/release/m20_watson_calibrate", "usr/bin/", "755"],
    ["target/release/m20_zcam_calibrate", "usr/bin/", "755"],
    ["target/release/m20_scam_calibrate", "usr/bin/", "755"],
    ["target/release/hpc_filter", "usr/bin/", "755"],
    ["target/release/nsyt_icc_calibrate", "usr/bin/", "755"],
    ["target/release/nsyt_idc_calibrate", "usr/bin/", "755"],
    ["README.md", "usr/share/doc/mars_raw_utils/README", "644"],
    ["src/cal/*png", "usr/share/mars_raw_utils/data/", "644"],
]



[lib]
name = "mars_raw_utils"

[[bin]]
name = "msl_mahli_calibrate"
path = "bin/msl_mahli_calibrate.rs"

[[bin]]
name = "msl_mcam_calibrate"
path = "bin/msl_mcam_calibrate.rs"

[[bin]]
name = "m20_zcam_calibrate"
path = "bin/m20_zcam_calibrate.rs"

[[bin]]
name = "msl_fetch_raw"
path = "bin/msl_fetch_raw.rs"

[[bin]]
name = "m20_fetch_raw"
path = "bin/m20_fetch_raw.rs"

[[bin]]
name = "nsyt_icc_calibrate"
path = "bin/nsyt_icc_calibrate.rs"

[[bin]]
name = "nsyt_idc_calibrate"
path = "bin/nsyt_idc_calibrate.rs"

[[bin]]
name = "msl_ecam_calibrate"
path = "bin/msl_ecam_calibrate.rs"

[[bin]]
name = "hpc_filter"
path = "bin/hpc_filter.rs"

[[bin]]
name = "m20_ecam_calibrate"
path = "bin/m20_ecam_calibrate.rs"

[[bin]]
name = "m20_watson_calibrate"
path = "bin/m20_watson_calibrate.rs"

[[bin]]
name = "m20_scam_calibrate"
path = "bin/m20_scam_calibrate.rs"

[features]
default = ["opencv-4"]
clang-runtime = ["clang/runtime"]
opencv-4 = []
opencv-32 = []
opencv-34 = []
contrib = []
docs-only = []

[dependencies]
image = "0.23.14"
clap = "2.33.3"
spice = "0.1.0"
opencv = "0.52.0"
zip = "0.5.11"
json = "0.12.4"
chrono = "0.4.19"
clang-sys = "1.1.1"
const_format = "0.2.14"
reqwest = { version = "0.11.2", features = ["blocking"] }
platforms = "1.1.0"

[build-dependencies]
clang = { version = "1.0", features = ["clang_6_0"], optional = true } 
[package.metadata.rpm]
package = "mars_raw_utils"

[package.metadata.rpm.cargo]
buildflags = ["--release"]

[package.metadata.rpm.targets]
mars_raw_utils = { path = "/usr/bin/mars_raw_utils" }
