FROM centos:centos8

RUN yum group install -y "Development Tools"

RUN bash -c "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y"

ENV PATH="/root/.cargo/bin:${PATH}"

WORKDIR /build
RUN cargo install cargo-rpm

RUN yum install -y clang clang-devel clang-libs clang-tools-extra openssl-devel libstdc++ libstdc++-devel

# Install OpenCV4 here...

COPY . .
RUN cargo build
