use mars_raw_utils::msl::{latest::LatestData, remote::fetch_latest, remote::remote_fetch};

#[tokio::test]
async fn test_msl_latest() {
    fetch_latest().await.expect("Failed to fetch latest data");
}

#[tokio::test]
async fn test_msl_instrument_fetches() {
    let f: Vec<String> = vec![];

    remote_fetch(
        &[String::from("MAST_LEFT")],
        5,
        Some(0),
        3119,
        3119,
        false,
        true,
        &f,
        false,
        "",
    )
    .await
    .unwrap();
    remote_fetch(
        &[String::from("MAST_RIGHT")],
        5,
        Some(0),
        3119,
        3119,
        false,
        true,
        &f,
        false,
        "",
    )
    .await
    .unwrap();
    remote_fetch(
        &[String::from("MARDI")],
        5,
        Some(0),
        3119,
        3119,
        false,
        true,
        &f,
        false,
        "",
    )
    .await
    .unwrap();
    remote_fetch(
        &[String::from("MAHLI")],
        5,
        Some(0),
        3119,
        3119,
        false,
        true,
        &f,
        false,
        "",
    )
    .await
    .unwrap();
    remote_fetch(
        &[String::from("CHEMCAM_RMI")],
        5,
        Some(0),
        3119,
        3119,
        false,
        true,
        &f,
        false,
        "",
    )
    .await
    .unwrap();
    remote_fetch(
        &[String::from("MAST_LEFT")],
        5,
        Some(0),
        3119,
        3119,
        false,
        true,
        &f,
        false,
        "",
    )
    .await
    .unwrap();
    remote_fetch(
        &[String::from("NAV_RIGHT_A")],
        5,
        Some(0),
        3119,
        3119,
        false,
        true,
        &f,
        false,
        "",
    )
    .await
    .unwrap();
    remote_fetch(
        &[String::from("NAV_RIGHT_B")],
        5,
        Some(0),
        3119,
        3119,
        false,
        true,
        &f,
        false,
        "",
    )
    .await
    .unwrap();
    remote_fetch(
        &[String::from("NAV_LEFT_A")],
        5,
        Some(0),
        3119,
        3119,
        false,
        true,
        &f,
        false,
        "",
    )
    .await
    .unwrap();
    remote_fetch(
        &[String::from("NAV_LEFT_B")],
        5,
        Some(0),
        3119,
        3119,
        false,
        true,
        &f,
        false,
        "",
    )
    .await
    .unwrap();
    remote_fetch(
        &[String::from("FHAZ_RIGHT_A")],
        5,
        Some(0),
        3119,
        3119,
        false,
        true,
        &f,
        false,
        "",
    )
    .await
    .unwrap();
    remote_fetch(
        &[String::from("FHAZ_RIGHT_B")],
        5,
        Some(0),
        3119,
        3119,
        false,
        true,
        &f,
        false,
        "",
    )
    .await
    .unwrap();
    remote_fetch(
        &[String::from("FHAZ_LEFT_A")],
        5,
        Some(0),
        3119,
        3119,
        false,
        true,
        &f,
        false,
        "",
    )
    .await
    .unwrap();
    remote_fetch(
        &[String::from("FHAZ_LEFT_B")],
        5,
        Some(0),
        3119,
        3119,
        false,
        true,
        &f,
        false,
        "",
    )
    .await
    .unwrap();
    remote_fetch(
        &[String::from("RHAZ_RIGHT_A")],
        5,
        Some(0),
        3119,
        3119,
        false,
        true,
        &f,
        false,
        "",
    )
    .await
    .unwrap();
    remote_fetch(
        &[String::from("RHAZ_RIGHT_B")],
        5,
        Some(0),
        3119,
        3119,
        false,
        true,
        &f,
        false,
        "",
    )
    .await
    .unwrap();
    remote_fetch(
        &[String::from("RHAZ_LEFT_A")],
        5,
        Some(0),
        3119,
        3119,
        false,
        true,
        &f,
        false,
        "",
    )
    .await
    .unwrap();
    remote_fetch(
        &[String::from("RHAZ_LEFT_B")],
        5,
        Some(0),
        3119,
        3119,
        false,
        true,
        &f,
        false,
        "",
    )
    .await
    .unwrap();
}
